# Generated by Django 4.2.7 on 2023-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('text_welcome', models.CharField(max_length=1500)),
                ('text_timezone', models.CharField(max_length=1500)),
                ('text_timezone_changed', models.CharField(max_length=1500)),
                ('text_subscribe', models.CharField(max_length=1500)),
                ('text_today', models.CharField(max_length=1500)),
                ('text_tomorrow', models.CharField(max_length=1500)),
                ('text_settings', models.CharField(max_length=1500)),
                ('text_FAQHelp', models.CharField(max_length=1500)),
                ('button_menu_text_today', models.CharField(max_length=1500)),
                ('button_menu_text_tomorrow', models.CharField(max_length=1500)),
                ('button_menu_text_settings', models.CharField(max_length=1500)),
                ('button_menu_text_FAQHelp', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.BooleanField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_UTC',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
