<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2023-11-30 16:18
=======
# Generated by Django 4.2.7 on 2023-11-30 15:38
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('language_code', models.CharField(max_length=3)),
                ('text_welcome', models.CharField(max_length=1500)),
                ('text_timezone', models.CharField(max_length=1500)),
                ('text_timezone_changed', models.CharField(max_length=1500)),
                ('text_subscribe', models.CharField(max_length=1500)),
                ('text_today', models.CharField(max_length=1500)),
                ('text_tomorrow', models.CharField(max_length=1500)),
                ('text_settings', models.CharField(max_length=1500)),
                ('text_FAQHelp', models.CharField(max_length=1500)),
                ('button_menu_text_today', models.CharField(max_length=1500)),
                ('button_menu_text_tomorrow', models.CharField(max_length=1500)),
                ('button_menu_text_settings', models.CharField(max_length=1500)),
                ('button_menu_text_FAQHelp', models.CharField(max_length=1500)),
=======
                ('language_code', models.CharField(blank=True, max_length=255, null=True)),
>>>>>>> Stashed changes
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
<<<<<<< Updated upstream
            field=models.CharField(default='1', max_length=255),
=======
            field=models.CharField(default='ru', max_length=255),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification',
<<<<<<< Updated upstream
            field=models.BooleanField(default='1', max_length=255),
=======
            field=models.BooleanField(default=1, max_length=255),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_UTC',
<<<<<<< Updated upstream
            field=models.CharField(default='1', max_length=255),
=======
            field=models.CharField(default=0, max_length=255),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
    ]
