# Generated by Django 4.2.7 on 2023-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_language_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='button_menu_text_FAQHelp',
            field=models.CharField(default='test', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='button_menu_text_settings',
            field=models.CharField(default='test', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='button_menu_text_today',
            field=models.CharField(default='test', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='button_menu_text_tomorrow',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_FAQHelp',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_settings',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_subscribe',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_timezone',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_timezone_changed',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_today',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_tomorrow',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='text_welcome',
            field=models.CharField(default='1', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
