# Generated by Django 4.2.7 on 2023-11-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_language_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification',
            field=models.BooleanField(),
        ),
    ]
