# Generated by Django 4.2.7 on 2023-11-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_userprofile_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='text_subscribe',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
