# Generated by Django 4.2.7 on 2023-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_userprofile_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_link', models.CharField(max_length=255)),
                ('amount', models.IntegerField(max_length=200000)),
                ('date', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='text_subscribe',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
