# Generated by Django 4.2.7 on 2023-12-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_language_text_subscribe_and_more'),
        ('bot', '0005_giveaways_alter_language_text_subscribe_and_more'),
    ]

    operations = [
    ]
