# Generated by Django 4.2.7 on 2023-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaways',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
