# Generated by Django 4.2.7 on 2023-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_language_text_folder_alter_giveaways_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='language',
            name='text_FAQHelp',
            field=models.TextField(max_length=1500),
        ),
    ]
